[package]
edition = "2021"
license = "MIT"
name = "acr"
version = "0.1.2"

[dependencies]
anthropic = {path = "../anthropic"}
base64 = "0.22.1"
clap = {version = "4.5.16", features = ["derive"]}
dotenvy = "0.15.7"
infer = "0.16.0"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
