[package]
edition = "2021"
license = "MIT"
name = "anthropic"
version = "0.1.0"

[dependencies]
reqwest = {version = "0.12", features = ["json"]}
serde = {version = "1.0", features = ["derive"]}
tokio = {version = "1", features = ["full"]}
